feat: LlamaIndex Workflows on Cloud Run via Llama Deploy
GoogleCloudPlatform/generative-ai pull request #1294
Opened 2024-10-18 17:50 UTC by noabenefraim

# Description

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [ ] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [ ] You are listed as the author in your notebook or README file.
  - [ ] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).
- [ ] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [ ] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-10-22 18:56 UTC, holtskinner commented on gemini/sample-apps/llamadeploy-on-cloud-run/data/gatsby.txt
Please remove this file from the PR. Large data files like this should be uploaded to Google Cloud Storage. I added this to our public GCS bucket here:

`gs://github-repo/generative-ai/sample-apps/llamadeploy-on-cloud-run/gatsby.txt`

Either have the user download it with gsutil or send the gcs path directly to gemini if possible

2024-10-22 18:57 UTC, holtskinner commented on .github/actions/spelling/excludes.txt
> +^\Qgemini/sample-apps/llamadeploy-on-cloud-run/data/gatsby.txt\E$
```suggestion
```

2024-10-22 19:01 UTC, holtskinner requested changes

2024-10-23 21:21 UTC, noabenefraim commented on gemini/sample-apps/llamadeploy-on-cloud-run/data/gatsby.txt
Removed! Added download instructions to the README.md.

2024-10-23 21:21 UTC, noabenefraim commented on .github/actions/spelling/excludes.txt
> +^\Qgemini/sample-apps/llamadeploy-on-cloud-run/data/gatsby.txt\E$
Removed.

2024-10-23 21:23 UTC, noabenefraim commented on gemini/sample-apps/llamadeploy-on-cloud-run/workflow.py
> +            print(node)
Good for the logs, to see what data was retrieved.

2024-10-23 21:29 UTC, noabenefraim commented on gemini/sample-apps/llamadeploy-on-cloud-run/workflow.py
> +                new_nodes.append(new_node)
I don't think so. ```model_validate``` only takes in an object, but I can't further assign variable to the object being validated.

2024-10-23 21:29 UTC, noabenefraim commented on gemini/sample-apps/llamadeploy-on-cloud-run/workflow.py
> +        # stop_fn = self.default_stop_fn
Done.

2024-10-23 21:32 UTC, noabenefraim commented on gemini/sample-apps/llamadeploy-on-cloud-run/workflow.py
> +            print(node)
Resolving for now, feel free to unresolve @holtskinner

2024-10-24 01:26 UTC, holtskinner approved these changes

2024-10-24 01:26 UTC, merged