feat: Add sample notebook for AI Quick Build Experience back-end
GoogleCloudPlatform/generative-ai pull request #1300
Opened 2024-10-21 18:19 UTC by ZackAkil

# Description
Add sample notebook for AI Quick Build Experience back-end 

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [x] You are listed as the author in your notebook or README file.
  - [x] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).
- [x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [x] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [x] Appropriate docs were updated (if necessary)

2024-10-21 18:36 UTC, holtskinner commented
Looks like you created two different notebooks, one with the name in all caps and one with lowercase. Can you remove the uppercase one?

Also, Can you remove the outputs with images? It makes the notebooks slow to load and difficult to review.

2024-10-22 16:36 UTC, holtskinner requested changes

2024-10-22 16:36 UTC, holtskinner commented on gemini/use-cases/education/ai_quick_build_experience_backend.ipynb
Not able to make inline comments because of images.

---
- Add more context in the overview for what "AI Quick Build" is and where to learn more about it.
- Remove the cell outputs for library install
- Put all imports at the top of the notebook - similar to other notebooks in this repo.
- Add typing for method parameters and return values throughout.
- Can you change the Images to be sent to Gemini direct from GCS? Use `Image.from_uri()` - Saves the extra downloading
- Optional: Change all instances of gemini 1.5 flash/gemini 1.5 pro to use auto-updating version or 002
- Optional: Change Imagen to use Imagen3
- In `judging_response_schema_player` - Change `"Score"` to be lowercase
- Can you make a dict or other data structure to hold the player info/pictures to help keep it organized? (And use the same data throughout the notebook instead of redefining it)
- In your JSON Schemas, can you be consistent on using `snake_case` or `camelCase` for properties?
- Be consistent on spelling of `favorite` (US or UK English :P)
- Some of the displayed outputs can probably be removed from the notebook, most probably aren't needed.

Will add more later

2024-10-23 14:56 UTC, ZackAkil commented on gemini/use-cases/education/ai_quick_build_experience_backend.ipynb
made changes
re: library imports, moved the more global ones to the top, move the ones that are specific to the sections to the top of the sections.
re: Image.from_uri(), added comment saying can use that but kept loading from local so that its easier for developers to play with and add their own images
re: Imagen3, will update when image editing is available 
removed all unnecessary outputs, got the notebook down to 2mb

2024-10-23 15:00 UTC, merged