feat: Added Code to generate creative advertisements using  Gemini and Imagen3
GoogleCloudPlatform/generative-ai pull request #1395
Opened 2024-11-12 17:33 UTC by ankuljain09

# Description

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [ ] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [ ] You are listed as the author in your notebook or README file.
  - [ ] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).
- [ ] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [ ] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-11-12 17:36 UTC, holtskinner commented on vision/use-cases/advertisment-creation-using-gemini-and-imagen3/GoogleSans-Bold.ttf
Remove this file from the PR

2024-11-12 17:40 UTC, holtskinner requested changes

2024-11-12 17:40 UTC, holtskinner commented on vision/use-cases/advertisment-creation-using-gemini-and-imagen3/sample_gemini_imagen_adImage_1.png
Remove these images from the repo. Add them to Google Cloud Storage. We have a public bucket to use.

2024-11-12 17:40 UTC, holtskinner commented on vision/use-cases/advertisment-creation-using-gemini-and-imagen3/advertisment_creation_using_gemini_and_imagen3.ipynb
The folder & notebook name is misspelled. `advertisement`

2024-11-12 17:40 UTC, holtskinner commented on vision/use-cases/advertisment-creation-using-gemini-and-imagen3/advertisment_creation_using_gemini_and_imagen3.ipynb
Remove image output from notebook, it makes the file very large and difficult to review.

2024-11-12 17:40 UTC, holtskinner commented on vision/use-cases/advertisment-creation-using-gemini-and-imagen3/advertisment_creation_using_gemini_and_imagen3.ipynb
Add typing for all function parameters/return values.

2024-11-12 17:46 UTC, holtskinner commented on vision/use-cases/advertisment-creation-using-gemini-and-imagen3/advertisment_creation_using_gemini_and_imagen3.ipynb
Also, I'd recommend just calling it `advertisement-creation` (gemini and imagen3 is redundant)

2024-11-13 15:20 UTC, ankuljain09 commented on vision/use-cases/advertisment-creation-using-gemini-and-imagen3/advertisment_creation_using_gemini_and_imagen3.ipynb
Removed the image output

2024-11-13 15:21 UTC, ankuljain09 commented on vision/use-cases/advertisment-creation-using-gemini-and-imagen3/sample_gemini_imagen_adImage_1.png
Removed the images from the repo and referred the public GCS paths in the gradio code

2024-11-13 15:21 UTC, ankuljain09 commented on vision/use-cases/advertisment-creation-using-gemini-and-imagen3/GoogleSans-Bold.ttf
Removed the file, Added description to help user download the Roboto.ttf file and use it in the code.

2024-11-13 16:14 UTC, holtskinner commented on vision/use-cases/advertisement-creation/advertisement_creation.ipynb
> +        "![Screenshot 2024-11-08 at 5.16.00 PM.png](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB20AAASnCAYAAADG/+MUAAAMP2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAhGQEnoTRKQEkBJCCyC9CDZCEiCUGANBx
Replace the base64 image with this:

```md
![Architecture](https://storage.googleapis.com/github-repo/generative-ai/vision/advertisement-creation/architecture.png)
```

2024-11-13 16:15 UTC, holtskinner commented on vision/use-cases/advertisement-creation/advertisement_creation.ipynb
> +        "##Restart runtime\n",
```suggestion
        "## Restart runtime\n",
```

2024-11-13 16:15 UTC, holtskinner commented on vision/use-cases/advertisement-creation/advertisement_creation.ipynb
> +        "## Generate Images using Imagen3\n",
```suggestion
        "## Generate Images using Imagen 3\n",
```

2024-11-13 16:26 UTC, holtskinner commented on vision/use-cases/advertisement-creation/advertisement_creation.ipynb
> +        "# Generate ad text using gemini-1.5-flash model\n",
```suggestion
        "# Generate ad text using Gemini 1.5 Flash\n",
```

2024-11-13 16:27 UTC, holtskinner commented on vision/use-cases/advertisement-creation/advertisement_creation.ipynb
> +        "Before running the below code, download a font file (eg. [Roboto](https://fonts.google.com/selection?selection.family=Roboto:wght@700)) and provide the font .ttf file path in the below varia
```suggestion
        "Before running the below code, download a font file (eg. [Roboto](https://fonts.google.com/selection?selection.family=Roboto:wght@700)) and provide the font `.ttf` file path in the below variable `downloaded_font_path`"
```

2024-11-13 16:28 UTC, holtskinner commented on vision/use-cases/advertisement-creation/advertisement_creation.ipynb
> +        "## Styling the Adverstisement Image\n",
```suggestion
        "## Styling the Advertisement Image\n",
```

2024-11-13 16:28 UTC, holtskinner commented on .github/CODEOWNERS
> +/generative-ai/vision/use-cases/advertisment-creation-using-gemini-and-imagen3    @ankuljain09 @koyelguha
```suggestion
/generative-ai/vision/use-cases/advertisement-creation-using-gemini-and-imagen3    @ankuljain09 @koyelguha
```

2024-11-13 16:28 UTC, holtskinner commented on vision/use-cases/advertisement-creation/advertisement_creation.ipynb
> +        "## Generate advertisment text using Gemini"
```suggestion
        "## Generate advertisement text using Gemini"
```

2024-11-13 16:28 UTC, holtskinner commented on vision/use-cases/advertisement-creation/advertisement_creation.ipynb
> +        "# Function to create advertisment\n",
```suggestion
        "# Function to create advertisement\n",
```

2024-11-13 17:02 UTC, ankuljain09 commented on vision/use-cases/advertisement-creation/advertisement_creation.ipynb
> +        "![Screenshot 2024-11-08 at 5.16.00 PM.png](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB20AAASnCAYAAADG/+MUAAAMP2lDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkJDQAhGQEnoTRKQEkBJCCyC9CDZCEiCUGANBx
Replaced

2024-11-14 18:10 UTC, merged