feat: Gemini SFT using multiple images and text
GoogleCloudPlatform/generative-ai pull request #1458
Opened 2024-11-23 01:03 UTC by inardini

# Description

This notebook demonstrates how to fine-tune the Gemini 1.5 Pro model for change detection task (spot differences) with the Vertex AI Supervised Tuning feature using multiple images and text as inputs.

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [x] You are listed as the author in your notebook or README file.
  - [x] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).
- [x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [x] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [x] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-11-25 16:07 UTC, holtskinner requested changes
Just a few comments

2024-11-25 16:07 UTC, holtskinner commented on gemini/tuning/supervised_finetuning_using_gemini_on_multiple_images.ipynb
> +        "        ]\n",
Same as before, I recommend pandas

2024-11-25 20:21 UTC, inardini commented on gemini/tuning/supervised_finetuning_using_gemini_on_multiple_images.ipynb
> +        "def save_jsonlines(instances: list[dict[str, Any]], file_path: str) -> None:\n",
tried but it does not generate the expected format which requires square brackets as part of the request

2024-11-25 20:22 UTC, inardini commented on gemini/tuning/supervised_finetuning_using_gemini_on_multiple_images.ipynb
> +        "                                \"fileUri\": f\"{image_path}.png\",\n",
it is how the documentation requires to pass the call

2024-11-25 20:22 UTC, inardini commented on gemini/tuning/supervised_finetuning_using_gemini_on_multiple_images.ipynb
> +        "        ]\n",
same as before

2024-11-26 17:02 UTC, inardini commented on gemini/tuning/supervised_finetuning_using_gemini_on_multiple_images.ipynb
> +        "    # Read and parse the jsonlines file\n",
same as below

2024-11-26 17:57 UTC, gericdong approved these changes

2024-11-27 15:24 UTC, holtskinner approved these changes

2024-11-27 15:24 UTC, merged