feat: Serving Gemma 2 with multiple LoRA adapters with Text Generation Inference (TGI) on Vertex AI notebook
GoogleCloudPlatform/generative-ai pull request #1586
Opened 2024-12-30 14:38 UTC by inardini

# Description

This notebook showcases how to deploy Gemma 2 2B from the Hugging Face Hub with multiple LoRA adapters fine-tuned for different purposes such as coding, or SQL using HuggingFace's Text Generation Inference (TGI) Deep Learning Container (DLC) in combination with a [custom handler](https://huggingface.co/docs/inference-endpoints/en/guides/custom_handler#create-custom-inference-handler) on Vertex AI.

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [x] You are listed as the author in your notebook or README file.
  - [x] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).
- [x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [x] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [x] Appropriate docs were updated (if necessary)

2025-01-02 15:45 UTC, holtskinner requested changes

2025-01-02 15:45 UTC, holtskinner commented on open-models/README.md
> +- [serving/vertex_ai_tgi_gemma_multi_lora_adapters_deployment.ipynb](./serving/vertex_ai_tgi_gemma_multi_lora_adapters_deployment.ipynb) - This notebook showcases how to deploy Gemma 2 from the Huggi
```suggestion
- [serving/vertex_ai_tgi_gemma_multi_lora_adapters_deployment.ipynb](./serving/vertex_ai_tgi_gemma_multi_lora_adapters_deployment.ipynb) - This notebook showcases how to deploy Gemma 2 from Hugging Face Hub with multiple LoRA adapters fine-tuned for different purposes such as coding, or SQL using Hugging Face's Text Generation Inference (TGI) Deep Learning Container (DLC) in combination with a custom handler on Vertex AI.
```

2025-01-06 08:17 UTC, inardini commented on open-models/README.md
> +- [serving/vertex_ai_tgi_gemma_multi_lora_adapters_deployment.ipynb](./serving/vertex_ai_tgi_gemma_multi_lora_adapters_deployment.ipynb) - This notebook showcases how to deploy Gemma 2 from the Huggi
done

2025-01-06 08:23 UTC, inardini commented on open-models/serving/vertex_ai_tgi_gemma_multi_lora_adapters_deployment.ipynb
> +        "handler_module = '''\n",
I understand the formatting requirement. For learning purposes, don't you think it is better to have the code the code embedded in the notebook? This approach would allow learners to review the code alongside the explanations and possibly have a deeper understanding of the code's logic.

2025-01-07 09:59 UTC, inardini commented on open-models/serving/vertex_ai_tgi_gemma_multi_lora_adapters_deployment.ipynb
> +        "handler_module = '''\n",
@holtskinner let me know what you think

2025-01-09 16:53 UTC, holtskinner commented on open-models/serving/vertex_ai_tgi_gemma_multi_lora_adapters_deployment.ipynb
> +        "handler_module = '''\n",
We can just leave it as is, I suppose.

2025-01-09 16:57 UTC, merged