feat: Added and linted all the files for Agent-Assist App.
GoogleCloudPlatform/generative-ai pull request #541
Opened 2024-04-16 07:12 UTC by nitchandak

# Description

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [x] You are listed as the author in your notebook or README file.
  - [x] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).
- [x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [x] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [x] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-04-16 15:22 UTC, holtskinner requested changes
This is an incredibly large Pull Request.

Quite a few of these files probably shouldn't be checked into a Git Repository.

We have a Google Cloud Storage Bucket [`gs://github-repo/`](https://console.cloud.google.com/storage/browser/github-repo) for related files for Notebooks/Sample Apps in this repo. I can upload files for you.

Can you please go through the files and determine which of them are needed for the app to function? The others, like the pickle, JSON, txt, images should probably go in the bucket and be linked from the other files to prevent the repo from getting too large.

2024-04-16 15:25 UTC, holtskinner commented on gemini/sample-apps/agent-assist/backend/src/config.py
> +    "PROJECT_ID": "teamindrdhanush",
Remove this Project ID and replace with a placeholder

2024-04-16 15:25 UTC, holtskinner commented on gemini/sample-apps/agent-assist/backend/src/config.py
> +    "company_email": "teamkavachinsurance@gmail.com",
Replace with a placeholder

2024-04-16 15:25 UTC, holtskinner commented on gemini/sample-apps/agent-assist/.gitignore
> +package.json
package.json shouldn't be put in gitignore.

Can you also move these to the main repo .gitignore?

2024-04-19 16:54 UTC, holtskinner commented
I added the files you provided to GCS. These are the new paths:


- `backend/src/chatbot_dir/agents/search_agent/preprocessing/table/one_shot/*.txt` → 
`gs://github-repo/generative-ai/sample-apps/agent-assist/data-prep/*.txt`
- `backend/src/data` → `gs://github-repo/generative-ai/sample-apps/agent-assist/backend-data/`
- `frontend/src/*.png` → `gs://github-repo/generative-ai/sample-apps/agent-assist/frontend-images`

I also moved images used in the README should be moved as well and adjusted the links in the README.

2024-04-19 16:55 UTC, holtskinner commented
I'd still recommend doing some refactoring before I'll go into a deeper review. There's too much to examine at this point.

2024-04-24 05:33 UTC, nitchandak commented
> I'd still recommend doing some refactoring before I'll go into a deeper review. There's too much to examine at this point.

What kind of refactoring should we do?

2024-04-24 15:32 UTC, holtskinner commented
> > I'd still recommend doing some refactoring before I'll go into a deeper review. There's too much to examine at this point.
> 
> What kind of refactoring should we do?

I would recommend finding ways to simplify this application code to make it easier to read/understand.

2024-05-17 19:58 UTC, holtskinner commented
Please resolve spelling errors shown in this check https://github.com/GoogleCloudPlatform/generative-ai/actions/runs/9101630581/attempts/1#summary-25019286805

For items that aren't errors, you can follow the instructions to add them to the list of approved terms.

2024-05-28 18:30 UTC, holtskinner commented
# Pull Request Summary from Gemini ✨
None

# Code Analysis from Gemini ✨
## Code Analysis and Suggestions:

**File: .github/actions/spelling/patterns.txt**

* **Bug:** The pattern `\b(?:[Ll]og|[Ss]ign) in to\b` matches `log in to`, `sign in to`, and also `login to`, which is not the intended behavior. This will result in false positives.
* **Improvement:** To avoid matching `login to`, modify the pattern to: `\b(?:[Ll]og|[Ss]ign) (?:in|into)\b` 

**File: gemini/sample-apps/agent-assist/.gitignore**

* **Improvement:** The `.gitignore` file can be improved by grouping similar patterns together and using wildcard characters for better readability and maintainability. 
    * For example, instead of listing `backend/src/my_config.py` and `backend/*.pyc`, use `backend/src/*.py` and `backend/*.pyc` respectively. 
    * The `frontend/npm-debug.log*`, `frontend/yarn-debug.log*` and `frontend/yarn-error.log*` can be combined into `frontend/*.log*`

**File: gemini/sample-apps/agent-assist/README.md**

* **Improvement:**  The README.md can be further improved with better formatting and structuring. 
    * Use headings (H2, H3, etc.) consistently to divide sections and create a clear hierarchy. 
    * Add a table of contents for easy navigation. 
    * Use markdown syntax to bold and italicize important terms. 
    * Consider adding a section for contributing to the project, with guidelines and instructions. 

**File: gemini/sample-apps/agent-assist/SETUP.md**

* **Improvement:**  The SETUP.md can be improved with more detailed explanations of each step, and clear instructions on how to run commands. 
    * Provide a section explaining the necessary environment setup and dependencies.
    * For each step, describe the purpose of the command and what it achieves. 
    * Include any potential errors and troubleshooting tips for common issues. 

**File: gemini/sample-apps/agent-assist/backend/Dockerfile**

* **Improvement:** The `Dockerfile` can be improved with more detailed comments explaining the steps involved in building the docker image. 
    * Add comments for each `COPY`, `RUN`, `EXPOSE`, and `ENTRYPOINT` command explaining their purpose.
    * Consider using a multi-stage build to separate the build process from the final image. 
    * The `EXPOSE 8000` command should be placed after `WORKDIR /app/src/` to ensure the correct working directory.

**File: gemini/sample-apps/agent-assist/backend/src/apis/__init__.py**

* **Improvement:** This file is empty and can be removed. 

**File: gemini/sample-apps/agent-assist/backend/src/apis/calendar.py**

* **Improvement:**  The `get_calendar_events()` function could be improved by adding error handling for cases where the Calendar API call fails.
    * Use a `try-except` block to catch any exceptions.
    * Log errors to help in debugging.
    * Return a meaningful error message to the user if an exception occurs.

**File: gemini/sample-apps/agent-assist/backend/src/apis/chatbot.py**

* **Improvement:** The `chatbot_entry` function could be improved by handling cases where `data.get("chat_history")` or `data.get("query")` is None. 
    * Add a check for null values and handle them accordingly.
    * Return an error message to the user if the input data is invalid.
    * The `logs.json` file is used for logging but should not be committed to the repository. It is a good practice to use a more robust logging mechanism.

**File: gemini/sample-apps/agent-assist/backend/src/apis/customermanagement.py**

* **Improvement:** The `get_customer_management_data` function should include error handling for cases where the file `data/policy.json` is not found.
    * Use a `try-except` block to catch any exceptions.
    * Log errors to help in debugging.
    * Return a meaningful error message to the user if an exception occurs.
    * In `get_metrics_data`,  `get_lapsed_customers` and `get_chart_data`, consider using a dictionary instead of a list to store the data. It will make the code more readable and easier to access specific data points.

**File: gemini/sample-apps/agent-assist/backend/src/apis/email.py**

* **Improvement:** The `mail()` function could be improved by adding error handling for cases where the email sending process fails.
    * Use a `try-except` block to catch any exceptions.
    * Log errors to help in debugging.
    * Return a meaningful error message to the user if an exception occurs.

**File: gemini/sample-apps/agent-assist/backend/src/apis/generate_mail.py**

* **Improvement:** The `generate_mail()` and `extract_and_send_mail()` functions could be improved by adding error handling for cases where the `TextBison` call fails.
    * Use a `try-except` block to catch any exceptions.
    * Log errors to help in debugging.
    * Return a meaningful error message to the user if an exception occurs.

**File: gemini/sample-apps/agent-assist/backend/src/apis/kanban.py**

* **Improvement:**  The `update_kanban_data` function should include error handling for cases where the file `data/real_users_db.json` is not found.
    * Use a `try-except` block to catch any exceptions.
    * Log errors to help in debugging.
    * Return a meaningful error message to the user if an exception occurs.

**File: gemini/sample-apps/agent-assist/backend/src/apis/leadsandsales.py**

* **Improvement:** The `get_leads_and_sales_data` function should include error handling for cases where the file `data/policy.json` is not found.
    * Use a `try-except` block to catch any exceptions.
    * Log errors to help in debugging.
    * Return a meaningful error message to the user if an exception occurs.
    * Consider using a dictionary instead of a list to store the `platform_data` in `get_different_platform_data`.

**File: gemini/sample-apps/agent-assist/backend/src/apis/marketingandoutreach.py**

* **Improvement:** The `get_marketing_and_outreach_data` function should include error handling for cases where the file `data/likes.json` is not found.
    * Use a `try-except` block to catch any exceptions.
    * Log errors to help in debugging.
    * Return a meaningful error message to the user if an exception occurs.
    * The `get_metrics_data` function is quite long and could be refactored to make it more readable and maintainable. Consider breaking it down into smaller functions based on its logic.

**File: gemini/sample-apps/agent-assist/backend/src/apis/performance.py**

* **Improvement:** The `get_performance_data` function should include error handling for cases where the file `data/policy.json` is not found.
    * Use a `try-except` block to catch any exceptions.
    * Log errors to help in debugging.
    * Return a meaningful error message to the user if an exception occurs.
    * In `get_month_data`,  consider using a dictionary instead of a list to store the data. It will make the code more readable and easier to access specific data points.

**File: gemini/sample-apps/agent-assist/backend/src/apis/requirements.txt**

* **Improvement:** The `requirements.txt` file should specify the versions of the required packages to ensure consistency and avoid potential issues caused by version conflicts.

**File: gemini/sample-apps/agent-assist/backend/src/backend.py**

* **Improvement:** The `backend.py` file could be improved by using a more robust logging mechanism instead of relying on `print` statements.
    * Implement a logging framework like `logging` to log messages to a file or a console.
    * The `get_real_users_contacted` and `get_real_users_potential` functions can be combined into a single function that takes a boolean parameter to indicate whether to fetch contacted or potential users.

**File: gemini/sample-apps/agent-assist/backend/src/chatbot_dir/__init__.py**

* **Improvement:** This file is empty and can be removed.

**File: gemini/sample-apps/agent-assist/backend/src/chatbot_dir/agents/__init__.py**

* **Improvement:** This file is empty and can be removed.

**File: gemini/sample-apps/agent-assist/backend/src/chatbot_dir [...]

2024-05-28 18:37 UTC, holtskinner commented
# Pull Request Summary from Gemini ✨
None

# Code Analysis from Gemini ✨
## Analysis of Pull Request: feat: Added and linted all the files for Agent-Assist App.

This Pull Request introduces a new feature: an Agent Assist application built with Generative AI and Google Cloud. While the code is generally well-structured and the Pull Request follows the `CONTRIBUTING` guidelines, there are some potential improvements and bugs to address:

### .github/actions/spelling/patterns.txt

**Improvements:**

* **Clarity of Comments:** The comments could be more concise and specific. For example, "Questionably acceptable forms of `in to`" could be replaced with "Match 'log in to' or 'sign in to'."
* **Redundant Patterns:** Some patterns are similar or redundant with existing ones.  For instance, "git.io" is a specific case covered by the general GitHub URL pattern. Consider removing redundant patterns.
* **Specificity for Google URLs:** While the Google URL patterns are comprehensive, consider making them more specific by including domain names like `google.com`, `googleusercontent.com`, etc., to reduce potential false positives.
* **Potential False Positives:** The pattern for `ls directory listings` could trigger on other text with similar sequences of characters. Consider refining the pattern for more precise matches.
* **Consistency in Code Style:** Use consistent spacing and indentation throughout the file for better readability.

**Code Snippets for Changes:**

```diff
--- a/.github/actions/spelling/patterns.txt
+++ b/.github/actions/spelling/patterns.txt
@@ -4,7 +4,7 @@
 # Automatically suggested patterns
 
 # hit-count: 654 file-count: 86
-# https/http/file urls
+# Match HTTPS/HTTP/FTP/File URLs
 (?:\b(?:https?|ftp|file)://)[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|]
 
 # hit-count: 98 file-count: 34
@@ -20,7 +20,7 @@
 # Python string prefix / binary prefix
 # Note that there's a high false positive rate, remove the `?=` and search for the regex to see if the matches seem like reasonable strings
 (?<!['"])\b(?:B|BR|Br|F|FR|Fr|R|RB|RF|Rb|Rf|U|UR|Ur|b|bR|br|f|fR|fr|r|rB|rF|rb|rf|u|uR|ur)['"](?=[A-Z]{3,}|[A-Z][a-z]{2,}|[a-z]{3,})
-
+# Match Kubernetes object suffix
 # hit-count: 19 file-count: 2
 # kubernetes object suffix
 [0-9a-f]{10}-\w{5}\s
@@ -32,6 +32,7 @@
 # Compiler flags (Windows / PowerShell)
 # This is a subset of the more general compiler flags pattern.
 # It avoids matching `-Path` to prevent it from being treated as `ath`
+# Match Compiler flags (Windows/PowerShell)
 (?:^|[\t ,"'`=(])-(?:[DPL](?=[A-Z]{2,})|[WXYlf](?=[A-Z]{2,}|[A-Z][a-z]|[a-z]{2,}))
 
 # hit-count: 13 file-count: 5
@@ -52,11 +53,13 @@
 # libraries
 \blib(?!rar(?:ies|y))(?=[a-z])
 
+# Match AWS VPC
 # hit-count: 8 file-count: 3
 # AWS VPC
 vpc-\w+
 
 # hit-count: 7 file-count: 7
+# Match UUIDs
 # uuid:
 \b[0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\b
 
@@ -81,10 +84,12 @@
 # integrity
 integrity=(['"])(?:\s*sha\d+-[-a-zA-Z=;:/0-9+]{40,})+\g{-1}
 
+# Match Curl arguments
 # hit-count: 1 file-count: 1
 # curl arguments
 \b(?:\\n|)curl(?:\.exe|)(?:\s+-[a-zA-Z]{1,2}\b)*(?:\s+-[a-zA-Z]{3,})(?:\s+-[a-zA-Z]+)*
 
+# Match pom.xml id fields
 # pom.xml id fields
 <\w+Id>[^<]+</
 
@@ -93,9 +98,11 @@
 # Personally, I prefer `log into`, but people object
 # https://www.tprteaching.com/log-into-log-in-to-login/
 \b(?:[Ll]og|[Ss]ign) in to\b
-
+# Match "to opt in"
 # to opt in
 \bto opt in\b
+
+# Match Acceptable Duplicates
 
 # acceptable duplicates
 # ls directory listings
@@ -123,7 +130,8 @@
 # Commit message -- Signed-off-by and friends
 ^\s*(?:(?:Based-on-patch|Co-authored|Helped|Mentored|Reported|Reviewed|Signed-off)-by|Thanks-to): (?:[^<]*<[^>]*>|[^<]*)\s*$
 
+# Match Autogenerated revert commit message
 # Autogenerated revert commit message
 ^This reverts commit [0-9a-f]{40}\.$
 
@@ -133,6 +141,7 @@
 # ignore long runs of a single character:
 \b([A-Za-z])\g{-1}{3,}\b
 
+# Match Non-English Words
 # hit-count: 40 file-count: 8
 # Non-English
 [a-zA-Z]*[ÀÁÂÃÄÅÆČÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝßàáâãäåæčçèéêëìíîïðñòóôõöøùúûüýÿĀāŁłŃńŅņŒœŚśŠšŜŝŸŽžź][a-zA-Z]{3}[a-zA-ZÀÁÂÃÄÅÆČÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝßàáâãäåæčçèéêëìíîïðñòóôõöøùúûüýÿĀāŁłŃńŅņŒœŚśŠšŜŝŸŽžź]*|[a-zA-Z]{3,}[ÀÁÂÃÄÅÆČÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝßàáâãäåæčçèéêëìíîïðñòóôõöøùúûüýÿĀāŁłŃńŅņŒœŚśŠšŜŝŸŽžź]|[ÀÁÂÃÄÅÆČÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝßàáâãäåæčçèéêëìíîïðñòóôõöøùúûüýÿĀāŁłŃńŅņŒœŚśŠšŜŝŸŽžź][a-zA-Z]{3,}
@@ -140,6 +149,7 @@
 # hit-count: 22 file-count: 1
 # ANSI color codes
 (?:\\(?:u00|x)1[Bb]|\x1b|\\u\{1[Bb]\})\[\d+(?:;\d+|)m
+
 
 # hit-count: 15 file-count: 3
 # base64 encoded content
@@ -164,37 +174,53 @@
 # While you could try to match `http://` and `https://` by using `s?` in `https?://`, sometimes there
 # YouTube url
 \b(?:(?:www\.|)youtube\.com|youtu.be)/(?:channel/|embed/|user/|playlist\?list=|watch\?v=|v/|)[-a-zA-Z0-9?&=_%]*
+# Match YouTube Music URL
 # YouTube music
 \bmusic\.youtube\.com/youtubei/v1/browse(?:[?&]\w+=[-a-zA-Z0-9?&=_]*)
+# Match YouTube Tag
 # YouTube tag
 <\s*youtube\s+id=['"][-a-zA-Z0-9?_]*['"]
+# Match YouTube image
 # YouTube image
 \bimg\.youtube\.com/vi/[-a-zA-Z0-9?&=_]*
+# Match Google Accounts URL
 # Google Accounts
 \baccounts.google.com/[-_/?=.:;+%&0-9a-zA-Z]*
+# Match Google Analytics URL
 # Google Analytics
 \bgoogle-analytics\.com/collect.[-0-9a-zA-Z?%=&_.~]*
+# Match Google APIs URL
 # Google APIs
 \bgoogleapis\.(?:com|dev)/[a-z]+/(?:v\d+/|)[a-z]+/[-@:./?=\w+|&]+
+# Match Google Storage URL
 # Google Storage
 \b[-a-zA-Z0-9.]*\bstorage\d*\.googleapis\.com(?:/\S*|)
+# Match Google Calendar URL
 # Google Calendar
 \bcalendar\.google\.com/calendar(?:/u/\d+|)/embed\?src=[@./?=\w&%]+
 \w+\@group\.calendar\.google\.com\b
+# Match Google DataStudio URL
 # Google DataStudio
 \bdatastudio\.google\.com/(?:(?:c/|)u/\d+/|)(?:embed/|)(?:open|reporting|datasources|s)/[-0-9a-zA-Z]+(?:/page/[-0-9a-zA-Z]+|)
 # The leading `/` here is as opposed to the `\b` above
 # ... a short way to match `https://` or `http://` since most urls have one of those prefixes
+# Match Google Docs URL
 # Google Docs
 /docs\.google\.com/[a-z]+/(?:ccc\?key=\w+|(?:u/\d+|d/(?:e/|)[0-9a-zA-Z_-]+/)?(?:edit\?[-\w=#.]*|/\?[\w=&]*|))
+# Match Google Drive URL
 # Google Drive
 \bdrive\.google\.com/(?:file/d/|open)[-0-9a-zA-Z_?=]*
+# Match Google Groups URL
 # Google Groups
 \bgroups\.google\.com(?:/[a-z]+/(?:#!|)[^/\s"]+)*
+# Match Google Maps URL
 # Google Maps
 \bmaps\.google\.com/maps\?[\w&;=]*
+# Match Google Themes URL
 # Google themes
 themes\.googleusercontent\.com/static/fonts/[^/\s"]+/v\d+/[^.]+.
+# Match Google CDN URL
 # Google CDN
 \bclients2\.google(?:usercontent|)\.com[-0-9a-zA-Z/.]*
+# Match Goo.gl URL
 # Goo.gl
 /goo\.gl/[a-zA-Z0-9]+
+# Match Google Chrome Store URL
 # Google Chrome Store
@@ -212,12 +238,15 @@
 # Google Fonts
 \bfonts\.(?:googleapis|gstatic)\.com/[-/?=:;+&0-9a-zA-Z]*
 # Google Forms
-\bforms\.gle/\w+
+# Match Google Scholar URL
 # Google Scholar
 \bscholar\.google\.com/citations\?user=[A-Za-z0-9_]+
+# Match Google Colab Research Drive URL
 # Google Colab Research Drive
 \bcolab\.research\.google\.com/drive/[-0-9a-zA-Z_?=]*
 
+# Match GitHub SHAs (API/Markdown)
+# Match GitHub SHAs (API/Markdown)
 # GitHub SHAs (api)
 \bapi.github\.com/repos(?:/[^/\s"]+){3}/[0-9a-f]+\b
 # GitHub SHAs (markdown)
@@ -225,17 +254,23 @@
 # GitHub SHAs
 \bgithub\.com(?:/[^/\s"]+){2}[@#][0-9a-f]+\b
 # GitHub SHA refs
-\[([0-9a-f]+)\]\(https://(?:www\.|)github\.com/[-\w]+/[-\w]+/commit/\g{-1}[0-9a-f]*
+# Match GitHub Wiki URL
 # GitHub wiki
 \bgithub\.com/(?:[^/]+/){2}wiki/(?:(?:[^/]+/|)_history|[^/]+(?:/_compare|)/[0-9a-f.]{40,})\b
+# Match Githubusercontent URL
 # githubusercontent
 /[-a-z0-9]+\.githubusercontent\.com/[-a-zA-Z0-9?&=_\/.]*
+# Match Githubassets URL
 # githubassets
 \bgithubassets.com/[0-9a-f]+(?:[-/\w.]+)
+# Match Gist GitHub URL
 # gist github
 \bgist\.github\.com/[^/\s"]+/[0-9a-f]+
+# Match Git.io URL
 # git.io
 \bgit\.io/[0-9a-zA-Z]+
+# Match GitHub JSON
 # GitHub JSON
 "node_id": "[-a-zA-Z=;:/0-9+_]*"
 # Contributor
@@ -243, [...]

2024-05-28 18:48 UTC, holtskinner commented
# Code Analysis from Gemini ✨
{analysis_output}
Generated at Commit: `1582197824823ad9df0897416119362cb3379b38`

2024-06-05 15:07 UTC, holtskinner commented
Closing due to inactivity. Please re-open if requested changes are made.

2024-06-05 15:07 UTC, closed without merging

2024-06-10 07:53 UTC, nitchandak commented
All the spelling errors are false positives and need to be added to the allowlist. We have used them in our code and most of them are either names of insurances, variables or people. Would be great if you could re-open the PR.

2024-06-10 09:22 UTC, nitchandak commented
There are also some python library names that have been marked as spelling errors.