feat: Add Customer Search Demo App
GoogleCloudPlatform/generative-ai pull request #546
Opened 2024-04-16 10:29 UTC by CodeChamp-SS

# Description

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [ ] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [ ] You are listed as the author in your notebook or README file.
  - [ ] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).
- [ ] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [ ] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2024-04-22 16:55 UTC, holtskinner requested changes
See comment. I will do a more thorough review once the files are cleaned up

2024-04-23 09:17 UTC, CodeChamp-SS commented
> @CodeChamp-SS Can you add a description of your sample app to the PR Description?
> 
> Also, all of the Images/PDF/CSV files make this PR quite large. These files should really be added to a Google Cloud Storage Bucket and linked in if needed, to reduce the size of the repository.
> 
> We have a public Google Cloud Storage Bucket [`gs://github-repo/`](https://console.cloud.google.com/storage/browser/github-repo) for related files for Notebooks/Sample Apps in this repo. I can upload files for you.

@holtskinner you may put the following files/folders in the GCS bucket:
gemini/sample-apps/customer-search/files/tables
gemini/sample-apps/customer-search/files/CymbalBankWebDeployed/assets
gemini/sample-apps/customer-search/files/FD_TnC.pdf
gemini/sample-apps/customer-search/files/Market_Summary.pdf

2024-04-23 15:27 UTC, holtskinner commented
@CodeChamp-SS I moved the requested files to GCS:

`gs://github-repo/generative-ai/sample-apps/customer-search/`

New Paths:

- `gemini/sample-apps/customer-search/files/tables` → `gs://github-repo/generative-ai/sample-apps/customer-search/tables`
- `gemini/sample-apps/customer-search/files/CymbalBankWebDeployed/assets` → `gs://github-repo/generative-ai/sample-apps/customer-search/assets/`
- `gemini/sample-apps/customer-search/files/FD_TnC.pdf` → `gs://github-repo/generative-ai/sample-apps/customer-search/FD_TnC.pdf`
- `gemini/sample-apps/customer-search/files/Market_Summary.pdf` → `gs://github-repo/generative-ai/sample-apps/customer-search/Market_Summary.pdf`

You can also access these through the public links https://storage.googleapis.com/github-repo/generative-ai/sample-apps/customer-search/FD_TnC.pdf

I also recommend moving the README images to GCS and linking them in this way.

2024-04-23 16:04 UTC, holtskinner requested changes
I'm stopping part way through to allow time to make some of the changes.

Overall there's a lot of duplicated code and most of this application seems to be overly complex. I would highly recommend refactoring and finding ways to reduce duplication and complexity. It will make the application code much more readable/understandable/maintainable.

2024-04-23 16:04 UTC, holtskinner commented on gemini/sample-apps/customer-search/functions/credit-card-imagen/main.py
> +        images[0].save(location="./gen-img1.png", include_generation_parameters=True)
You should be able to access the image base64 directly. https://github.com/googleapis/python-aiplatform/blob/118826ff88d6e0510dc67e37edfc16f646cb3489/vertexai/vision_models/_vision_models.py#L103C9-L103C21

2024-04-23 16:04 UTC, holtskinner commented on gemini/sample-apps/customer-search/functions/event-recommendationv2/main.py
Why is there an eventrecommendation v2 and v3?

2024-04-23 16:07 UTC, CodeChamp-SS commented
> @CodeChamp-SS I moved the requested files to GCS:
> 
> `gs://github-repo/generative-ai/sample-apps/customer-search/`
> 
> New Paths:
> 
> * `gemini/sample-apps/customer-search/files/tables` → `gs://github-repo/generative-ai/sample-apps/customer-search/tables`
> * `gemini/sample-apps/customer-search/files/CymbalBankWebDeployed/assets` → `gs://github-repo/generative-ai/sample-apps/customer-search/assets/`
> * `gemini/sample-apps/customer-search/files/FD_TnC.pdf` → `gs://github-repo/generative-ai/sample-apps/customer-search/FD_TnC.pdf`
> * `gemini/sample-apps/customer-search/files/Market_Summary.pdf` → `gs://github-repo/generative-ai/sample-apps/customer-search/Market_Summary.pdf`
> 
> You can also access these through the public links https://storage.googleapis.com/github-repo/generative-ai/sample-apps/customer-search/FD_TnC.pdf
> 
> I also recommend moving the remaining images for the README and app to GCS and linking them in this way.

Thanks! Will replace the images/files in the code with these.

2024-04-24 05:35 UTC, CodeChamp-SS commented on gemini/sample-apps/customer-search/files/CymbalBankWebDeployed/img/build-config.png
No they're no needed, I will remove these.

2024-04-24 05:38 UTC, CodeChamp-SS commented on gemini/sample-apps/customer-search/files/CymbalBankWebDeployed/public/cymbal-credit-cards.pdf
Missed this file, please add this one too in the GCS bucket.

2024-05-06 05:08 UTC, CodeChamp-SS commented on gemini/sample-apps/customer-search/files/CymbalBankWebDeployed/style/style_new.css
Initially we had two versions of css styling, removed the older one and renamed the file

2024-05-06 05:09 UTC, CodeChamp-SS commented on gemini/sample-apps/customer-search/files/tnc.jpeg
This is no longer used, deleted it

2024-05-06 05:11 UTC, CodeChamp-SS commented on gemini/sample-apps/customer-search/functions/account-health-summarisation-optimised/main.py
> +            debt_amount = int(row["debt"])
Have created a function now to get these values

2024-05-06 05:12 UTC, CodeChamp-SS commented on gemini/sample-apps/customer-search/functions/account-health-summarisation-optimised/main.py
> +    model = TextGenerationModel.from_pretrained("text-bison")
Have replaced text-bison with Gemini everywhere.

2024-05-06 05:13 UTC, CodeChamp-SS commented on gemini/sample-apps/customer-search/functions/event-recommendationv2/main.py
Renamed the functions to more meaningful names.

2024-05-06 05:13 UTC, CodeChamp-SS commented on gemini/sample-apps/customer-search/functions/create_fd/main.py
> +    print("Today = ", today)
Have removed unnecessary print statements from all the files.

2024-05-06 06:51 UTC, CodeChamp-SS commented on gemini/sample-apps/customer-search/files/init_bqml_and_vector_search.ipynb
moved them in the top directory

2024-05-21 05:53 UTC, CodeChamp-SS commented
Hi @holtskinner, we have tried to resolve the suggestions you made, the other lint errors. I have created a new pull request #700 , please review it again. Thanks!

2024-05-23 05:18 UTC, CodeChamp-SS commented
> Ok, you didn't need to make a new Pull Request for the changes, but it's okay.
> 
> Please close out this Pull Request if it's no longer needed.

this branch got a bit messy, so I thought creating a new one would be better.

2024-05-23 05:18 UTC, closed without merging