refactor: Updated tutorial on Vector Search using Langchain
GoogleCloudPlatform/generative-ai pull request #548
Opened 2024-04-16 10:47 UTC by Adi8885

# Description

This PR addresses
1. Updated [question_answering_documents_langchain.ipynb](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/use-cases/document-qa/question_answering_documents_langchain.ipynb) tutorial with latest API changes as per latest release from [langchain-google-vertexai](https://pypi.org/project/langchain-google-vertexai/)

2. Added self as contributor to .github/CODEOWNERS

2024-04-16 14:30 UTC, holtskinner commented on .github/CODEOWNERS
@Adi8885 You'll need to join the GoogleCloudPlatform organization at go/github for this to work.

2024-04-16 15:40 UTC, Adi8885 commented on .github/CODEOWNERS
@holtskinner Requested Access, awaiting grant

2024-04-16 15:59 UTC, holtskinner requested changes
Remove project ID

2024-04-18 04:57 UTC, Adi8885 commented on language/use-cases/document-qa/question_answering_documents_langchain_matching_engine.ipynb
>    },
Done

2024-04-18 17:46 UTC, holtskinner approved these changes

2024-04-19 16:37 UTC, merged