adding multi-language prompt feature: where user can see the english …
GoogleCloudPlatform/generative-ai pull request #925
Opened 2024-08-01 09:43 UTC by VJlaxmi

# Adding multi-language prompt feature

# Description

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [x] You are listed as the author in your notebook or README file.
  - [x] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).
- [x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [x] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [x] Appropriate docs were updated (if necessary)

Fixes N/A 🦕

## What did I do

Adding multi-language prompt feature: where the user can see the English prompt and the target language prompt requested by the user.

2024-08-01 17:03 UTC, holtskinner requested changes

2024-08-01 17:03 UTC, holtskinner commented on vision/use-cases/brochure-creation-using-imagen/brochure_creation_using_imagen.ipynb
> +    "REGION = \"us-central1\"\n",
Remove the actual project ID and just use the placeholder value. Also, remove the commented out sections
```suggestion
    "PROJECT_ID = \"[your-project-id]\"\n",
    "REGION = \"us-central1\"\n",
```

2024-08-01 17:03 UTC, holtskinner commented on vision/use-cases/brochure-creation-using-imagen/brochure_creation_using_imagen.ipynb
> +    "def get_supported_languages(project_id):\n",
Set all methods to have types for parameters and return values. Also use all built in classes wherever possible instead of generic dictionaries.

2024-08-01 17:03 UTC, holtskinner commented on vision/use-cases/brochure-creation-using-imagen/brochure_creation_using_imagen.ipynb
> +    },
Remove output

2024-08-07 06:07 UTC, VJlaxmi reviewed
i have made the necessary changes

2024-08-07 06:38 UTC, VJlaxmi commented on vision/use-cases/brochure-creation-using-imagen/brochure_creation_using_imagen.ipynb
> +    },
corrected!

2024-08-07 06:38 UTC, VJlaxmi commented
can you please check the notebook and accept pull request?

2024-08-07 06:38 UTC, closed without merging