feat: add rag eval pipeline for ops
GoogleCloudPlatform/generative-ai pull request #987
Opened 2024-08-26 23:26 UTC by inardini

# This notebook shows how you can use Vertex AI Pipelines to build a GenAI Model Evaluation Batch pipeline to evaluate a question-answering task with Rapid Eval API and DataflowML.

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [x] You are listed as the author in your notebook or README file.
  - [x] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).
- [x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [x] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [x] Appropriate docs were updated (if necessary)

2024-08-29 16:55 UTC, holtskinner commented on gemini/evaluation/evaluate_rag_pipeline.ipynb
General Question - Can you check that what you're writing here doesn't overlap too much with the content in #996 from @jsondai

2024-08-29 17:00 UTC, jsondai commented on gemini/evaluation/evaluate_rag_pipeline.ipynb
Our team's PM Irina wanted to move all "pipeline" based eval into a "legacy" folder since they are not the recommended way to run Gen AI Eval Service after the SDK-based product is launched to GA.

2024-09-19 18:24 UTC, holtskinner requested changes
Just a few comments.

I'm good to approve once the spelling issues are corrected or terms added to the allowlist.

https://github.com/GoogleCloudPlatform/generative-ai/actions/runs/10945338382?pr=987

2024-09-19 18:24 UTC, holtskinner commented on gemini/evaluation/evaluate_rag_pipeline.ipynb
> +        "This notebook shows how you can use Vertex AI Pipelines to build a GenAI Model Evaluation Batch pipeline to evaluate a question-answering task with Rapid Eval API and DataflowML.\n",
```suggestion
        "This notebook shows how you can use Vertex AI Pipelines to build a Gen AI Model Evaluation Batch pipeline to evaluate a question-answering task with Rapid Eval API and Dataflow ML.\n",
```

2024-09-19 18:24 UTC, holtskinner commented on gemini/evaluation/evaluate_rag_pipeline.ipynb
> +        "! pip3 install --upgrade --quiet pandas plotly multiprocess etils"
I generally recommend to put all of these in a single line

2024-09-19 18:24 UTC, holtskinner commented on gemini/evaluation/evaluate_rag_pipeline.ipynb
> +        "PROJECT_NUMBER = \"[your-project-number]\"  # @param {type:\"string\"}"
Would it be possible to fetch this from the Project ID so the user doesn't need to enter both?

```sh
gcloud projects describe $PROJECT_ID --format="value(projectNumber)"
```

2024-09-19 18:24 UTC, holtskinner commented on gemini/evaluation/evaluate_rag_pipeline.ipynb
> +        "from etils import epath\n",
Can you move these imports to the top?

2024-09-19 18:24 UTC, holtskinner commented on gemini/evaluation/evaluate_rag_pipeline.ipynb
> +        "TMP_URI.mkdir(parents=True, exist_ok=True)"
Minor nit, could you make these creations into a loop or something to reduce duplication?

2024-09-19 18:24 UTC, holtskinner commented on gemini/evaluation/evaluate_rag_pipeline.ipynb
> +        "from google_cloud_pipeline_components.v1.wait_gcp_resources import WaitGcpResourcesOp\n",
Can you move these imports to the top of the notebook?

2024-09-19 18:24 UTC, holtskinner commented on gemini/evaluation/evaluate_rag_pipeline.ipynb
> +        "Define an helper function to print evaluation results."
```suggestion
        "Define a helper function to print evaluation results."
```

2024-09-19 18:24 UTC, holtskinner commented on gemini/evaluation/evaluate_rag_pipeline.ipynb
> +        "custom_inference_module = '''\n",
For these code sections that are going to be saved to a file anyway, can you move them to separate Python files? (Maybe move this notebook into a dedicated folder)
You can wget them to download locally, then upload to the Dataflow resources?

2024-11-05 17:06 UTC, holtskinner commented
Closing due to inactivity. Please re-open once comments are addressed.

2024-11-05 17:06 UTC, closed without merging